version: '3'
services:
  nginx:
    build: ./docker-nginx
    links:
      - clipper-api
    volumes:
      - "/opt/clipper-front:/var/www/frontend"
    ports:
      - "80:80"
  clipper-api:
    image: "eu.gcr.io/focus-mechanic-212210/clipper-api"
    command: ["start", "--rabbitmq=amqp://clipper:clipper@rabbitmq:5672",
    "--ci=clipper-ci:8080", "--cd=clipper-cd:8080"] # TODO: Prime admin password from secrets
    restart: "always"
    links:
     - postgres
     - rabbitmq
     - clipper-ci
     - clipper-cd
  clipper-ci:
    image: "eu.gcr.io/focus-mechanic-212210/clipper-ci"
    command: ["start", "--rabbitmq=amqp://clipper:clipper@rabbitmq:5672",
     "--gcr=eu.gcr.io/focus-mechanic-212210/", "--json=/opt/clipper-ci-secrets/secret.json",
     "--builder=eu.gcr.io/focus-mechanic-212210/ci-builder"]
    restart: "always"
    links:
      - postgres
      - rabbitmq
    volumes:
      - "/opt/clipper-ci-secrets/secret.json:/opt/secrets/secret.json" # Actually usless as docker daemon runs outside the container
      - "/var/run/docker.sock:/var/run/docker.sock"
  clipper-cd:
    image: "eu.gcr.io/focus-mechanic-212210/clipper-cd"
    command: ["start", "--rabbitmq=amqp://clipper:clipper@rabbitmq:5672",
    "--ci=clipper-ci:8080"]
    restart: "always"
    links:
      - postgres
      - redis
      - clipper-ci
      - rabbitmq
    volumes:
      - "/opt/clipper-cd-config:/config/.kube"
  redis:
    image: "redis:5.0.3"
    restart: "always"
  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "clipper"
      POSTGRES_PASSWORD: "clipper" # Wow, much secure
      POSTGRES_DB: "clipper"
      PGDATA: "/opt/db"
    volumes:
     - "/opt/clipper-db:/opt/db"
  rabbitmq:
    image: "rabbitmq:3.7.8-management"
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "clipper"
      RABBITMQ_DEFAULT_PASS: "clipper" # TODO: Move credentials to secrets