version: '3'
services:
  nginx:
    build: ./docker-nginx
    links:
      - clipper-api
    volumes:
      - "/opt/clipper-front:/var/www/frontend"
    ports:
      - "80:80"
  clipper-api:
    image: "eu.gcr.io/focus-mechanic-212210/clipper-api"
    command: "start --rabbitmq=amqp://clipper:clipper@rabbitmq:5672" # TODO: Prime admin password from secrets
    ports:
     - "8080"
    restart: "always"
    links:
     - redis
     - postgres
     - rabbitmq
  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "clipper"
      POSTGRES_PASSWORD: "clipper" # Wow, much secure
      POSTGRES_DB: "clipper"
      PGDATA: "/opt/db"
    volumes:
     - "/opt/clipper-db:/opt/db"
  redis:
    image: "redis:alpine"
  rabbitmq:
    image: "rabbitmq:3.7.8"
    environment:
      RABBITMQ_DEFAULT_USER: "clipper"
      RABBITMQ_DEFAULT_PASS: "clipper" # TODO: Move credentials to secrets